{
 "title": "NeuralChainNet",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "\bCurrent Block",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.chain/head/block.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block time",
   "type": "graph",
   "description": "Average blocktime",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Seconds per block",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "geth.chain/head/block.gauge",
     "query": "SELECT 10 / difference(max(\"value\"))  FROM \"geth.chain/head/block.gauge\" WHERE $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Txes pending",
   "type": "singlestat",
   "description": "Txes pending",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.txpool/pending.count",
     "query": "SELECT mean(\"value\") FROM \"geth.chain/head/receipt.gauge\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Messages per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Messages in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.eth/consensus/tendermint/in/packets.meter",
     "query": "SELECT mean(\"m1\") FROM \"geth.eth/consensus/tendermint/in/packets.meter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Messages per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Messages out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.eth/consensus/tendermint/out/packets.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proposal wait time",
   "type": "graph",
   "description": "Average wait time for each block",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Seconds",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.eth/consensus/tendermint/proposalwait.timer",
     "query": "SELECT 10 /non_negative_difference(mean(\"count\")) FROM \"geth.eth/consensus/tendermint/proposalwait.timer\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Round",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Round number / second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.eth/consensus/tendermint/rounds.meter",
     "query": "SELECT non_negative_difference(mean(\"count\"))/10 FROM \"geth.eth/consensus/tendermint/rounds.meter\" WHERE $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trafic in",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Avg message (Kb/s)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.eth/consensus/tendermint/in/traffic.meter",
     "query": "SELECT mean(\"mean\")/1000 FROM \"geth.eth/consensus/tendermint/in/traffic.meter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trafic out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Avg message (Kb/s)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.eth/consensus/tendermint/out/traffic.meter",
     "query": "SELECT mean(\"mean\")/ 1000 FROM \"geth.eth/consensus/tendermint/out/traffic.meter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}